version: '2'

networks:
  default-network:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: deployment/local/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
    container_name: letters_parser_app
    networks:
      - default-network